apiVersion: batch/v1
kind: Job
metadata:
  name: dynatrace-setup-job
spec:
  template:
    spec:
      containers:
      - name: dynatrace-setup
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      serviceAccountName: keptn-default
      restartPolicy: Never
  backoffLimit: 0